### PR TITLE
RenduGitRepo

### PR DESCRIPTION
**Pull request by arikhativa**

### CODE REVIEW

**Comment by arikhativa** [comment]
Hey :)
I have created a local git server (.git_server.git) and connected rendu & grading to it.
also added a file & pull check

**Comment by JCluzet** [comment]
Hi arikhativa 👋

Whaw! Thank you so much for the effort you put into 42-EXAM.
However after testing your commit, the fix is not done using the push (Git) but using the render/ folder directly.

How does your solution work? It creates a temporary git repo which is reclone afterwards for the fix? Or is this one cloned? 

Anyway, thanks a lot for the energy you put into this.
I would be happy to integrate Git to the exam in order to have an identical exam to the real one from 42.
However, it will take me some time to understand how it all works and if it is flawless.

**Comment by arikhativa** [comment]
Sure thing :)
i'll try to explain.

The basic idea is to use git [Local Protocol](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols)

in create_git_server.sh, I create the "server" git repo and init it with the "--bare" flag.
this makes the repo a "Bare Repository" and not the normal "Non-Bare Repository" that most programers are familiar with.
(the repos on github are bare for example).

then I create rendu & grading, init them normally and set them to the local server with
`git remote add origin $SERVER_DIR`

now we have one central "server" and 2 "clients".

in the correction scripts I just pull the new changes and check what happened.

if you something is not clear let me know :)

**Comment by JCluzet** [comment]
I'm sorry, your idea is really good but unfortunately I think it's easier (knowing that the program runs only locally) not to add a git server.
It could complicate things, it will be more complicated to use the program without network for example. 
This will remain the only difference with the real 42 exam.
And the students will have to remember that they have to use Git.
Thanks anyway for your PullRequest which was a good job :)

**Comment by arikhativa** [comment]
oh i wish you would add it.. i think it is a cool feature
but i understand that you want to keep it simple.

just one thing, I don't understand this line:
> It could complicate things, it will be more complicated to use the program without network for example.
my change does not use the internet at all, so i'm not sure what you meant.

anyway, is there a way for me to help with this project?
do you have ideas that you want to implement?
I think this is a very cool initiative :)

**Pull request closed without merging**
