### PR TITLE
Fixes and Improvements for ExamRank04

### PR DESCRIPTION
**Pull request by hcivici**
# Fixes
### test.sh
- Removed the "|" at the end of the last test which clearly violated subject.txt (*followed by nothing*)
> we will never try a "|" immediately followed or preceded by nothing or "|" or ";"
- *cd* wouldn't fail if it had more than 1 args
### microshell.c 
- By executing one command at a time:
-> All the commands in the same **pipeline** that should have started at the same time would wait one before themself to finish executing
-> Code would rely on pipe buffer capacity
-> free_all() wasn't actually assigning NULL to the *ptr* but to the local variable (misunderstanding of how pointers work)
- Now all commands in the same **pipeline** get executed and then get waitpid()'ed. free_all() works as intended.
- Fixed fd leak right before executing the programs which lets writers continue writing to a pipe instead of causing them to get SIGPIPE and terminate (in a normal scenario where all read ends of a pipe is closed). Both read and write ends were leaking.

# Improvements
### test.sh
- Added more *cd* tests for errors
- Added cases ";abc" and "|xyz" to test string comparison
- Added 2 tests to check if **waitpid()** is used properly
-> **waitpid()** right after every fork should fail
-> Not using **waitpid()** at all should fail
- A function to create and serve a file that can fill up a pipe buffer and block final write (This is also **indirectly** testing if waitpid is used properly in a more complex format)
- Added fd leak test
### microshell.c
- Removed (seemingly) unnecessary checks when creating and closing pipes
- Changed main algorithm to execute commands in a pipeline all at once

# Notes
- I am not really a big fan of making a lot of assumptions for a code to work properly. Some of the tests I have added may not work if something lags for a second or so
- There might be better ways to trace fork() and waitpid() system calls
- I am not really sure if leaving hints and some explanations on **test.sh** would be ok as it is also shown in traces
- **Need more testing especially on MacOS**
```
git clone https://github.com/hcivici/42_EXAM.git 42_EXAM_test_hcivici && cd 42_EXAM_test_hcivici && make
```

### CODE REVIEW

**Comment by hcivici** [comment]
--> Second Commit <--
# Fixes
- Fixed fd leak on **microshell.c** before executing the programs which lets writers continue writing to a pipe instead of causing them to get SIGPIPE and terminate (in a normal scenario where all read ends of a pipe is closed). Both read and write ends were leaking.

# Improvements
- Added fd leak test to **test.sh**

**Comment by JCluzet** [comment]
Hey @hcivici 👋

Wow, I'm genuinely impressed with your pull request! It's clear you've put a lot of effort into these fixes and improvements for **ExamRank04**. Your attention to detail and dedication to enhancing the project's functionality are truly commendable.

From what I can see, your changes to `test.sh` and `microshell.c` are well-executed.

A huge thank you for your outstanding contribution. We are really lucky to have someone like you on board. Keep up the great work!

If you want the **Grademe+** status, give me your `$USER`.
Have a great day, and, thanks again!

**Comment by hcivici** [comment]
Hi @JCluzet

You are welcome ❤️ 
My `$USER` is same as my github username: `hcivici`

Thank you for building this great tool that helps students to train for upcoming exams 🙂 
Have a nice day!

**Comment by JCluzet** [comment]
This PullRequest create 1 bug on ExamRank04 reported on this issue : #149

**Comment by hcivici** [comment]
Not a bug, a feature 🤠

**Pull request merged**
