### PR TITLE
added exercise print_bits

### PR DESCRIPTION
**Pull request by Cerberus2290**
I would like to add the exercise 'print_bits' to Student part - exam02 - Level 1
Took the exam today and it appeared.
I'm unsure if my tester.sh is correct.
I hope I followed the contribution guidelines.
All the best
tstrassb @ 42 Wolfsburg

### CODE REVIEW

**Comment by JCluzet** [comment]
I'll check it out as soon as I can, thanks for your contribution :)

**Comment by Cerberus2290** [comment]
👍

**Comment by JCluzet** [comment]
Thanks :), if you want to get VIP status on Grademe/42_EXAM just tell me your username on your computer, `echo $USER `

**Comment by Cerberus2290** [comment]
Hey thanks for merging. What username do you mean? My intra? Or github?

**Comment by JCluzet** [comment]
The USER of your computer, you can get it by doing `echo $USER`

**Comment by Cerberus2290** [comment]
I'm using multiple computers with different OS. You can use the username: tstrassb
Thank you!

**Comment by JCluzet** [comment]
I just added you, sorry for the wait, if you have another username on another machine that you use often you can also give it to me.

**Pull request merged**
